"""
CoChem-SHIFT: Stage 2.0 - The Physics Dispatcher & Solvation Router
Filename: cochem_shift_engine.py

This module dynamically builds ORCA 6.1.1 input files for NMR/EPR calculations.
It enforces strict physical logic:
1. Relativistic Gate: Forces DKH2 / ZORA for heavy elements (Z > 30).
2. Dynamic Internal Referencing: Generates an identical compute template for the TMS standard.
3. Solvation Router: Flags protic solvents for explicit micro-solvation handling.
"""

import json
import os
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional

# SHIFT-04: Complete atomic number dictionary for elements 1 to 118
ATOMIC_NUMBERS = {
    'H': 1, 'He': 2, 'Li': 3, 'Be': 4, 'B': 5, 'C': 6, 'N': 7, 'O': 8, 'F': 9, 'Ne': 10,
    'Na': 11, 'Mg': 12, 'Al': 13, 'Si': 14, 'P': 15, 'S': 16, 'Cl': 17, 'Ar': 18, 'K': 19, 'Ca': 20,
    'Sc': 21, 'Ti': 22, 'V': 23, 'Cr': 24, 'Mn': 25, 'Fe': 26, 'Co': 27, 'Ni': 28, 'Cu': 29, 'Zn': 30,
    'Ga': 31, 'Ge': 32, 'As': 33, 'Se': 34, 'Br': 35, 'Kr': 36, 'Rb': 37, 'Sr': 38, 'Y': 39, 'Zr': 40,
    'Nb': 41, 'Mo': 42, 'Tc': 43, 'Ru': 44, 'Rh': 45, 'Pd': 46, 'Ag': 47, 'Cd': 48, 'In': 49, 'Sn': 50,
    'Sb': 51, 'Te': 52, 'I': 53, 'Xe': 54, 'Cs': 55, 'Ba': 56, 'La': 57, 'Ce': 58, 'Pr': 59, 'Nd': 60,
    'Pm': 61, 'Sm': 62, 'Eu': 63, 'Gd': 64, 'Tb': 65, 'Dy': 66, 'Ho': 67, 'Er': 68, 'Tm': 69, 'Yb': 70,
    'Lu': 71, 'Hf': 72, 'Ta': 73, 'W': 74, 'Re': 75, 'Os': 76, 'Ir': 77, 'Pt': 78, 'Au': 79, 'Hg': 80,
    'Tl': 81, 'Pb': 82, 'Bi': 83, 'Po': 84, 'At': 85, 'Rn': 86, 'Fr': 87, 'Ra': 88, 'Ac': 89, 'Th': 90,
    'Pa': 91, 'U': 92, 'Np': 93, 'Pu': 94, 'Am': 95, 'Cm': 96, 'Bk': 97, 'Cf': 98, 'Es': 99, 'Fm': 100
}

PROTIC_SOLVENTS = ["Water", "Methanol", "Ethanol", "D2O", "CD3OD"]

# Default ideal TMS structure (Si(CH3)4) coordinates (Angstroms)
DEFAULT_TMS_XYZ = """17
Tetramethylsilane (TMS) Ideal Reference Standard
Si         0.000000    0.000000    0.000000
C          1.061000    1.061000    1.061000
H          0.512000    1.956000    1.365000
H          1.956000    0.512000    1.365000
H          1.365000    1.365000    0.061000
C         -1.061000   -1.061000    1.061000
H         -0.512000   -1.956000    1.365000
H         -1.365000   -1.365000    0.061000
H         -1.956000   -0.512000    1.365000
C          1.061000   -1.061000   -1.061000
H          1.956000   -0.512000   -1.365000
H          1.365000   -1.365000   -0.061000
H          0.512000   -1.956000   -1.365000
C         -1.061000    1.061000   -1.061000
H         -1.365000    1.365000   -0.061000
H         -0.512000    1.956000   -1.365000
H         -1.956000    0.512000   -1.365000
"""

class SHIFTPhysicsDispatcher:
    def __init__(self, workspace_path: str):
        self.workspace = Path(workspace_path)
        self.registry_path = self.workspace / "cochem_shift_registry.json"
        self.registry = self._load_registry()
        
    def _get_artifact_dir(self) -> Path:
        """
        SHIFT-19: Get the artifact directory path from environment variable or workspace.
        """
        artifact_dir = os.getenv('COCHEM_ARTIFACT_DIR')
        if artifact_dir:
            return Path(artifact_dir)
        else:
            return self.workspace / "artifacts"

    def _load_registry(self) -> Dict[str, Any]:
        """Loads the registry generated by Stage 1.0."""
        if not self.registry_path.exists():
            raise FileNotFoundError("SHIFT registry not found. Run Stage 1.0 Ingestion first.")
        with open(self.registry_path, "r") as f:
            return json.load(f)

    def _check_relativistic_gate(self, xyz_path: Path) -> bool:
        """Parses the XYZ file to determine if heavy elements (Z > 30) are present."""
        if not xyz_path.exists():
            print(f"⚠️ Geometry file {xyz_path} missing. Defaulting to Non-Relativistic.")
            return False
            
        with open(xyz_path, "r") as f:
            lines = f.readlines()[2:]  # Skip atom count and comment line
            
        for line in lines:
            parts = line.split()
            if parts:
                element = parts[0].strip().capitalize()
                # SHIFT-04: Full element mapping
                z_num = ATOMIC_NUMBERS.get(element, 0)
                if z_num > 30:
                    print(f"⚛️ Heavy element detected ({element}, Z={z_num}). Activating Relativistic Gate.")
                    return True
        return False

    def _route_solvation(self, solvent: str) -> Tuple[str, bool]:
        """Determines the ORCA solvent block and checks if explicit micro-solvation is needed."""
        needs_micro_solvation = solvent in PROTIC_SOLVENTS
        if needs_micro_solvation:
            print(f"💧 Protic solvent detected ({solvent}). Flagging for explicit micro-solvation.")
            
        # Using SMD as the default robust implicit model for NMR
        orca_solvent_block = f"%cpcm smd true\n smdsolvent \"{solvent}\"\nend"
        return orca_solvent_block, needs_micro_solvation

    def _build_orca_command(
        self,
        tier: str = "T2-PBE0-D4",
        is_relativistic: bool = False,
        rel_hamiltonian: str = "ZORA",
        is_deuterium: bool = False,
        use_calibrated_mace: bool = False
    ) -> str:
        """
        Constructs v4 Method Matrix ORCA NMR command string.
        SHIFT-01: Replaced GOLD/SILVER/BRONZE tiering with T1, T2, T3 tiers.
        SHIFT-02: Eliminated hardcoded uncalibrated %mace block unless explicitly requested with calibration.
        SHIFT-03: Enforces pcSseg-3 basis for Deuterium.
        """
        tier_upper = tier.upper()
        if "T1" in tier_upper or "BRONZE" in tier_upper:
            base_cmd = "! NMR GIAO r2SCAN-3c def2/J"
        elif "T3" in tier_upper or "GOLD" in tier_upper:
            basis = "pcSseg-3" if not is_relativistic else "ZORA-def2-QZVPP"
            base_cmd = f"! NMR GIAO PBE0-D4 {basis} def2/J"
        else:  # T2-PBE0-D4 (Default)
            basis = "pcSseg-2" if not is_deuterium else "pcSseg-3"
            base_cmd = f"! NMR GIAO PBE0-D4 {basis} def2/J"

        if is_relativistic:
            if rel_hamiltonian.upper() == "DKH2":
                base_cmd += " DKH2 DKH-def2-TZVPP SARC/J"
            else:
                base_cmd += " ZORA ZORA-def2-TZVPP SARC/J"

        if use_calibrated_mace:
            base_cmd += "\n%mace\n  Active true\n  Model Thesseus_NMR\nend"

        template = f"{base_cmd}\n\n%nmr\n  CalculateShielding true\n  CalculateSSCC true\nend\n"
        return template

    def _build_orca_template(
        self,
        is_relativistic: bool,
        solvent_block: str = "",
        tier: str = "T2-PBE0-D4",
        rel_hamiltonian: str = "ZORA",
        is_deuterium: bool = False,
        use_calibrated_mace: bool = False
    ) -> str:
        """
        Constructs the physics-aware ORCA command string based on the calculation tier and solvent block.
        """
        tier_upper = tier.upper()
        if "T1" in tier_upper or "BRONZE" in tier_upper:
            base_cmd = "! NMR GIAO r2SCAN-3c def2/J"
        elif "T3" in tier_upper or "GOLD" in tier_upper:
            basis = "pcSseg-3" if not is_relativistic else "ZORA-def2-QZVPP"
            base_cmd = f"! NMR GIAO PBE0-D4 {basis} def2/J"
        else:  # T2-PBE0-D4 (Default)
            basis = "pcSseg-2" if not is_deuterium else "pcSseg-3"
            base_cmd = f"! NMR GIAO PBE0-D4 {basis} def2/J"

        if is_relativistic:
            if rel_hamiltonian.upper() == "DKH2":
                base_cmd += " DKH2 DKH-def2-TZVPP SARC/J"
            else:
                base_cmd += " ZORA ZORA-def2-TZVPP SARC/J"

        if use_calibrated_mace:
            base_cmd += "\n%mace\n  Active true\n  Model Thesseus_NMR\nend"

        if solvent_block:
            template = f"{base_cmd}\n\n{solvent_block}\n\n%nmr\n  CalculateShielding true\n  CalculateSSCC true\nend\n"
        else:
            template = f"{base_cmd}\n\n%nmr\n  CalculateShielding true\n  CalculateSSCC true\nend\n"
        return template

    def _ensure_reference_geometry(self) -> Path:
        """
        SHIFT-02: Generates TMS_ideal.xyz in workspace if not present.
        """
        tms_path = self.workspace / "TMS_ideal.xyz"
        if not tms_path.exists():
            tms_path.parent.mkdir(parents=True, exist_ok=True)
            with open(tms_path, "w") as f:
                f.write(DEFAULT_TMS_XYZ)
            print(f"Generated standard TMS reference structure at {tms_path}")
        return tms_path

    def dispatch(self, xyz_file: str, solvent: str = "Chloroform", is_deuterium: bool = False) -> Dict[str, Any]:
        """Generates the input files for the target molecule and the internal reference."""
        xyz_path = Path(xyz_file)
        target_name = xyz_path.stem
        raw_tier = self.registry.get("tier", "T2-PBE0-D4")
        
        # Map legacy tier names if found
        tier_map = {"GOLD": "T3-pcSseg-3", "SILVER": "T2-PBE0-D4", "BRONZE": "T1-r2SCAN-3c"}
        tier = tier_map.get(raw_tier.upper(), raw_tier)
        
        # Run Physics Checks
        is_relativistic = self._check_relativistic_gate(xyz_path)
        solvent_block, micro_solvation_flag = self._route_solvation(solvent)
        
        # Generate string template
        orca_header = self._build_orca_template(
            is_relativistic=is_relativistic,
            solvent_block=solvent_block,
            tier=tier,
            is_deuterium=is_deuterium
        )
        
        # 1. Target Molecule Input
        target_inp = self.workspace / f"{target_name}_nmr.inp"
        with open(target_inp, "w") as f:
            f.write(f"{orca_header}\n* xyzfile 0 1 {xyz_path.resolve()}\n")
            
        # 2. SHIFT-02: Ensure Reference Standard (TMS) geometry exists
        ref_xyz = self._ensure_reference_geometry()
        ref_inp = self.workspace / "TMS_reference_nmr.inp"
        with open(ref_inp, "w") as f:
            f.write(f"{orca_header}\n* xyzfile 0 1 {ref_xyz.resolve()}\n")
            
        print(f"✅ Dispatch complete. Target and Reference inputs generated at {tier} level.")
        
        # Update registry with run parameters
        self.registry["tier"] = tier
        self.registry["physics_params"] = {
            "relativistic": is_relativistic,
            "solvent": solvent,
            "micro_solvation_required": micro_solvation_flag,
            "target_inp": str(target_inp.name),
            "reference_inp": str(ref_inp.name),
            "is_deuterium": is_deuterium
        }
        
        with open(self.registry_path, "w") as f:
            json.dump(self.registry, f, indent=4)
            
        return self.registry