"""
CoChem-SHIFT: Stage 2.0 - The Physics Dispatcher & Solvation Router
Filename: cochem_shift_engine.py

This module dynamically builds ORCA 6.1.1 input files for NMR/EPR calculations.
It enforces strict physical logic:
1. Relativistic Gate: Forces DKH2 for heavy elements (Z > 30).
2. Dynamic Internal Referencing: Generates an identical compute template for the TMS standard.
3. Solvation Router: Flags protic solvents for explicit micro-solvation handling.
"""

import json
from pathlib import Path
from typing import Dict, Any, List, Tuple

# Simple atomic number map for Relativistic Gate (Z > 30 triggers DKH2)
ATOMIC_NUMBERS = {
    'H': 1, 'C': 6, 'N': 7, 'O': 8, 'F': 9, 'Si': 14, 'P': 15, 'S': 16, 'Cl': 17,
    'Br': 35, 'I': 53, 'Fe': 26, 'Pt': 78, 'Au': 79, 'Hg': 80, 'Pb': 82
}

PROTIC_SOLVENTS = ["Water", "Methanol", "Ethanol", "D2O", "CD3OD"]

class SHIFTPhysicsDispatcher:
    def __init__(self, workspace_path: str):
        self.workspace = Path(workspace_path)
        self.registry_path = self.workspace / "cochem_shift_registry.json"
        self.registry = self._load_registry()

    def _load_registry(self) -> Dict[str, Any]:
        """Loads the registry generated by Stage 1.0."""
        if not self.registry_path.exists():
            raise FileNotFoundError("SHIFT registry not found. Run Stage 1.0 Ingestion first.")
        with open(self.registry_path, "r") as f:
            return json.load(f)

    def _check_relativistic_gate(self, xyz_path: Path) -> bool:
        """Parses the XYZ file to determine if heavy elements (Z > 30) are present."""
        if not xyz_path.exists():
            print(f"⚠️ Geometry file {xyz_path} missing. Defaulting to Non-Relativistic.")
            return False
            
        with open(xyz_path, "r") as f:
            lines = f.readlines()[2:] # Skip atom count and comment line
            
        for line in lines:
            parts = line.split()
            if parts:
                element = parts[0].strip()
                # If Z > 30, we must use relativistic Hamiltonians
                if ATOMIC_NUMBERS.get(element, 0) > 30:
                    print(f"⚛️ Heavy element detected ({element}). Activating Relativistic Gate (DKH2).")
                    return True
        return False

    def _route_solvation(self, solvent: str) -> Tuple[str, bool]:
        """Determines the ORCA solvent block and checks if explicit micro-solvation is needed."""
        needs_micro_solvation = solvent in PROTIC_SOLVENTS
        if needs_micro_solvation:
            print(f"💧 Protic solvent detected ({solvent}). Flagging for explicit micro-solvation.")
            
        # Using SMD as the default robust implicit model for NMR
        orca_solvent_block = f"%cpcm smd true\n smdsolvent \"{solvent}\"\nend"
        return orca_solvent_block, needs_micro_solvation

    def _build_orca_template(self, is_relativistic: bool, solvent_block: str, tier: str) -> str:
        """Constructs the physics-aware ORCA command string based on the calculation tier."""
        # Baseline commands for NMR shielding and J-coupling
        base_cmd = "! NMR"
        
        # Tier-based method selection
        if tier in ["GOLD", "SILVER"]:
            base_cmd += " PBE0 def2-TZVPP def2/J"
        else: # BRONZE
            base_cmd += " r2SCAN-3c"

        # Inject Relativistic keywords if the gate was triggered
        if is_relativistic:
            base_cmd += " DKH2 def2-TZVPP/C"
            
        # Build the full template
        template = f"{base_cmd}\n\n{solvent_block}\n\n%nmr\n  CalculateShielding true\n  CalculateSSCC true\nend\n"
        return template

    def dispatch(self, xyz_file: str, solvent: str = "Chloroform") -> Dict[str, str]:
        """Generates the input files for the target molecule and the internal reference."""
        xyz_path = Path(xyz_file)
        target_name = xyz_path.stem
        tier = self.registry.get("tier", "BRONZE")
        
        # Run Physics Checks
        is_relativistic = self._check_relativistic_gate(xyz_path)
        solvent_block, micro_solvation_flag = self._route_solvation(solvent)
        
        # Generate string template
        orca_header = self._build_orca_template(is_relativistic, solvent_block, tier)
        
        # 1. Target Molecule Input
        target_inp = self.workspace / f"{target_name}_nmr.inp"
        with open(target_inp, "w") as f:
            f.write(f"{orca_header}\n* xyzfile 0 1 {xyz_path.resolve()}\n")
            
        # 2. Dynamic Internal Reference Input (e.g., TMS)
        # We enforce exactly the same parameters to ensure systematic error cancellation
        ref_inp = self.workspace / "TMS_reference_nmr.inp"
        with open(ref_inp, "w") as f:
            f.write(f"{orca_header}\n* xyzfile 0 1 TMS_ideal.xyz\n")
            
        print(f"✅ Dispatch complete. Target and Reference inputs generated at {tier} level.")
        
        # Update registry with run parameters
        self.registry["physics_params"] = {
            "relativistic": is_relativistic,
            "solvent": solvent,
            "micro_solvation_required": micro_solvation_flag,
            "target_inp": str(target_inp.name),
            "reference_inp": str(ref_inp.name)
        }
        
        with open(self.registry_path, "w") as f:
            json.dump(self.registry, f, indent=4)
            
        return self.registry

# Example usage for integration:
# dispatcher = SHIFTPhysicsDispatcher("./SHIFT_Workspace")
# dispatcher.dispatch("mol_conformer.xyz", solvent="D2O")